name: "GRACe Portal"
description: "Growers Regulatory Assistance & Compliance engine"
url: "https://www.chilldivision.co.nz"
codenotary: josiah@chilldivision.co.nz
version: "0.9.5"
slug: "grace_addon"
panel_icon: mdi:cannabis
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ingress: true
ingress_port: 8420
startup: application

map:
  - type: addon_config
    read_only: False
    path: /grace_config
